# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman"
gem 'middleman-s3_sync', '3.3.7'
gem "mime-types", "~> 3.0.0"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]


gem 'bitters'

gem "bootstrap-sass", :require => false

source 'https://rails-assets.org' do
  # Bower based assets files
  gem 'rails-assets-angular'
  gem 'rails-assets-angular-ui-router'
  gem 'rails-assets-lodash'
  gem 'rails-assets-restangular'


  # gem 'rails-assets-angucomplete-alt'
  # gem 'rails-assets-normalize-css'
  # gem 'rails-assets-bourbon'
  # gem 'rails-assets-neat'
  gem 'rails-assets-font-awesome'
end
